
service: ubic-food-stock-management
frameworkVersion: '2'

useDotenv: true

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: ${opt:stage}
  region: ap-northeast-1
  role: ${self:custom.environment.role}

custom:
  environment: ${file(./env.yml)}

resources:
      Resources:
        Bucket:
          Type: AWS::S3::Bucket
          Properties:
            BucketName: ${self:custom.environment.S3BUCKET}
        UBICFOOD:
          Type: AWS::DynamoDB::Table
          Properties:
            TableName: UBIC-FOOD
            AttributeDefinitions:
              - AttributeName: ID
                AttributeType: S
              - AttributeName: DataType
                AttributeType: S
            KeySchema:
              - AttributeName: ID
                KeyType: HASH
              - AttributeName: DataType
                KeyType: RANGE
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1

functions:
  bot:
    handler: bot/handler.index
    events:
      - http: POST bot
    environment: ${self:custom.environment}
  stock:
   handler: stock/handler.index
   events:
    - http: GET stock
  transaction:
    handler: transaction/handler.index
    events:
      - http: GET transaction
  user:
    handler: user/handler.index
    events:
      - http: GET user
    environment: ${self:custom.environment}